# =============================================================================
# INGRESS CONFIGURATION
# =============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankportal-ingress
  namespace: bankportal-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: bankportal.local
    http:
      paths:
      # Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bankportal-frontend-service
            port:
              number: 80
      # Auth Service API
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: bankportal-auth-service
            port:
              number: 8081
      # Account Service API
      - path: /api/accounts
        pathType: Prefix
        backend:
          service:
            name: bankportal-account-service
            port:
              number: 8082

---

# =============================================================================
# CONFIGMAP FOR NGINX CONFIGURATION
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: bankportal-dev
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Angular routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API Proxy zu Backend Services (K8s Service Names)
        location /api/auth/ {
            proxy_pass http://bankportal-auth-service:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/accounts/ {
            proxy_pass http://bankportal-account-service:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health check
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
