services:
  auth-service:
    image: bankportal-demo-auth-service:latest
    build: null
  account-service:
    image: bankportal-demo-account-service:latest
    build: null
  frontend:
    image: bankportal-demo-frontend:latest
    build: null
