# docker-compose.yml - BLEIBT für lokale Entwicklung

services:
  # PostgreSQL für Auth Service
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - bankportal-network

  # PostgreSQL für Account Service  
  postgres-account:
    image: postgres:15
    container_name: postgres-account
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_account_data:/var/lib/postgresql/data
    networks:
      - bankportal-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/authdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=mysecretkeymysecretkeymysecretkey123456
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - postgres-auth
    networks:
      - bankportal-network

  # Account Service
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-account:5432/accountdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=mysecretkeymysecretkeymysecretkey123456
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - postgres-account
    networks:
      - bankportal-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - account-service
    networks:
      - bankportal-network

volumes:
  postgres_auth_data:
  postgres_account_data:

networks:
  bankportal-network:
    driver: bridge