apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bankportal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: bankportal/account-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: POSTGRES_ACCOUNT_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_ACCOUNT_HOST
        - name: POSTGRES_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_ACCOUNT_PASSWORD
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: bankportal
spec:
  selector:
    app: account-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
