apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bankportal
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOG_LEVEL: "INFO"
  POSTGRES_AUTH_HOST: "postgres-auth-service"
  POSTGRES_AUTH_PORT: "5432"
  POSTGRES_AUTH_DB: "authdb"
  POSTGRES_ACCOUNT_HOST: "postgres-account-service"
  POSTGRES_ACCOUNT_PORT: "5432"
  POSTGRES_ACCOUNT_DB: "accountdb"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  ACCOUNT_SERVICE_URL: "http://account-service:8082"
  JWT_EXPIRATION: "3600"
