apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bankportal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bankportal/frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: ACCOUNT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACCOUNT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bankportal
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000  # Fester Port
  type: NodePort
