apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: bankportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_AUTH_DB
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_AUTH_PASSWORD
        volumeMounts:
        - name: postgres-auth-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-auth-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: bankportal
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
